/** Slug → display name lookup. Used anywhere ToolOutput.toolSlug needs a human-readable label. */
export const TOOL_NAME_MAP: Record<string, string> = {
  "blog-generator":      "Blog Generator",
  "yt-script":           "YT Script Writer",
  "thumbnail-ai":        "Thumbnail AI",
  "title-generator":     "Title Generator",
  "hook-writer":         "Hook Writer",
  "caption-generator":   "Caption Generator",
  "gst-invoice":         "GST Invoice",
  "expense-tracker":     "Expense Tracker",
  "quotation-generator": "Quotation Generator",
  "website-generator":   "Website Generator",
  "qr-generator":        "QR Generator",
  "whatsapp-bulk":       "WhatsApp Bulk",
  "salary-slip":         "Salary Slip",
  "resume-screener":     "Resume Screener",
  "jd-generator":        "JD Generator",
  "offer-letter":        "Offer Letter",
  "appraisal-draft":     "Appraisal Draft",
  "policy-generator":    "Policy Generator",
  "gst-calculator":      "GST Calculator",
  "tds-sheet":           "TDS Sheet",
  "legal-notice":        "Legal Notice",
  "nda-generator":       "NDA Generator",
  "legal-disclaimer":    "Legal Disclaimer",
  "email-subject":       "Email Subject",
  "linkedin-bio":        "LinkedIn Bio",
  "seo-auditor":         "SEO Auditor",
  "ad-copy":             "Ad Copy Writer",
};
